### ISSUE TITLE
Allow no composition derivatives in get_ATrhoXi_runtime

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/teqp#144]
See https://github.com/usnistgov/teqp/blob/ecfcd29b378a6a348e28f0adfcba8747be2c44f7/include/teqp/derivs.hpp#L261-L279

For you @Matthew-Boyd

**Comment by Matthew-Boyd** [comment]
Could you enable X(0,0,0) too? This would simplify calculating the reduced Helmholtz using dimensionless parameters by not having to back-calculate them from T and rho (via casts to get Tr and rhor).

**Comment by ianhbell** [comment]
Yeah, one sec. I vaguely recall there was a reason why that was a bad idea, but I don't remember what it was. Maybe it was elsewhere now that I think about it.

**Comment by ianhbell** [comment]
I needed a separate approach for 0,0,0, but I sorted it. You should be good to go
