### ISSUE TITLE
Add combination of multifluid + COSMO-SAC

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/teqp#151]
This one: https://doi.org/10.1016/j.fluid.2018.04.015 

Should hopefully help when there is the possibility of LLE; existing multi-fluid estimation schemes are woefully inadequate at predicting LLE.

**Comment by longemen3000** [comment]
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/master/src/models/EmpiricHelmholtz/MultiFluid/departure/GEDeparture.jl

**Comment by ianhbell** [comment]
Yes that one! Can Clapeyron.jl trace isothermal VLE with isochoric thermodynamics yet?

**Comment by ianhbell** [comment]
Only difference: with COSMO-SAC as GE model: https://doi.org/10.1016/j.fluid.2018.08.004

**Comment by longemen3000** [comment]
> Yes that one! Can Clapeyron.jl trace isothermal VLE with isochoric thermodynamics yet?

Not yet (in the main repo)

**Comment by ianhbell** [comment]
If you could it would be very useful (to me too). If I could use Clapeyron.jl rather than (or in addition to) implementing this method it would be nice.

**Comment by longemen3000** [comment]
on the model, `Clapeyron.HelmAct(components, activity = COSMOSACdsp)` should work (we have a function, `Clapeyron.excess_g_res` that returns the residual part of the excess gibbs energy).

on the tracers, which ones do you need?

**Comment by ianhbell** [comment]
Could you write me a runnable snippet that does this model for cyclopentane + acetone, an isothermal trace at 296 K? We have a similar system that has LLE and are trying to understand why no models we have access to predict the LLE
