### ISSUE TITLE
Problems after successfully building on Android ARM64 

### ISSUE THREAD

**Issue by defencedog** [usnistgov/teqp#29]
I have successfull build `.whl` & have installed it via `pip` following these guidelines
```
git clone --recursive https://github.com/usnistgov/teqp
cd teqp
python setup.py bdist_wheel
pip install dist/*.whl 
```
Log is attached of build / make 
[uk_install.log.txt](https://github.com/usnistgov/teqp/files/10067908/uk_install.log.txt)

However when i import it in `ipython` this problem occurs
```
In [2]: import teqp
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-56458343a8bd> in <cell line: 1>()
----> 1 import teqp

/data/data/com.termux/files/usr/lib/python3.9/site-packages/teqp/__init__.py in <module>
      2
      3 # Bring all entities from the extension module into this namespace
----> 4 from .teqp import *
      5 from .teqp import _make_model
      6

ImportError: dlopen failed: cannot locate symbol "PyObject_GenericGetDict" referenced by "/data/data/com.termux/files/usr/lib/python3.9/site-packages/teqp/teqp.cpython-39.so"...
```
No missing libraries either
```
ldd "/data/data/com.termux/files/usr/lib/python3.9/site-packages/teqp/teqp.cpython-39.so"
        libc++_shared.so => /data/data/com.termux/files/usr/lib/libc++_shared.so
        libdl.so => /system/lib64/libdl.so
        libm.so => /data/data/com.termux/files/usr/lib/libm.so
        libc.so => /system/lib64/libc.so
        ld-android.so => /system/lib64/ld-android.so
```

**Comment by ianhbell** [comment]
This is a new one for me, do you have the same problem if you install from the pre-built wheel with pip install teqp?

**Comment by defencedog** [comment]
@ianhbell **Problem solved** using this command instead: 
```
export LDFLAGS=-lpython3.9 && MATHLIB=m python setup.py bdist_wheel
```
I am on Samsung Galaxy Tab S7!

KIndly guide If I want to install this on another Android Tablet of same arhitecture & python version (...& same environment) will I only have to save the generate `.whl` ?

Regarding notebooks; mostly are running flawlessly bu this one is disturbing me `CheckCubics.ipynb`
![SmartSelect_20221122_191826_Via](https://user-images.githubusercontent.com/831749/203337288-7aa2f9ee-406f-4a09-87ab-816145a2a2cc.jpg)

**Comment by ianhbell** [comment]
Do the pre-built wheels not work? I could imagine that would be the case as I assume your tablet is running some flavor of linux.

Yes, I think the wheels *should* be compatible on your other tablet, but linux is very tricky to get binary compatible wheels.

The get_meta problem is a bug that I introduced in version 0.14.0 with the re-write of the python interface. I thought I got all the functions, but I missed this one, I'll fix it in 0.14.2 in the coming days.

**Comment by defencedog** [comment]
#Do the pre-built wheels not work? I could imagine that would be the case as I assume your tablet is running some flavor of linux.

No I have to built the `whl` but it worked without much hassle

**Comment by ianhbell** [comment]
I suppose I could built arm binaries too, but the python build matrix is already out of control: https://cibuildwheel.readthedocs.io/en/stable/

so I am going to leave this off for now.

**Comment by ianhbell** [comment]
0.14.2 was released, which fixes this problem with get_meta
