### ISSUE TITLE
How to calculate mass density of liquid hydrogen?

### ISSUE THREAD

**Issue by StefanPofahl** [usnistgov/teqp#32]
Thanks for your package, I saw your comment in: [Clapeyron/ladefault models?](https://github.com/ypaul21/Clapeyron.jl/issues/111)
that is the reason to work with your package.
I managed to calculate the mol mass according to your example:
```
import teqp
model = teqp.build_multifluid_model(["Hydrogen"], teqp.get_datapath())
anc = model.build_ancillaries()
T = 25.0 # [K]
rhoL, rhoV = anc.rhoL(T), anc.rhoV(T)
print('Densities are:', rhoL, rhoV, 'mol/m^3')
# these densities do not correspond to the true phase equilibrium solution, so we need to polish the solution:
Niter = 10
rhoLtrue, rhoVtrue = model.pure_VLE_T(T, rhoL, rhoV, Niter)
print('VLE densities are:', rhoLtrue, rhoVtrue, 'mol/m^3')
# convert to mass density of liquid hydrogen:
mol_mass_hydrogen = 2 * 1.008 / 1000 # kg/mol
rho_mass_L = rhoLtrue / mol_mass_hydrogen

```
All works fine (even in Julia / installed via: 
```
ENV["CONDA_JL_USE_MINIFORGE"] = "1"
import Conda; Conda.pip("install", "teqp")
```
)
Now I wonder, is this already the recommended methode?

**Comment by ianhbell** [comment]
Once you know the molar density, you get the specific density by multiplying by the molar mass. As you did, except backwards (multiply instead of divide).

Dimensionally:

(mol/m^3)*(kg/mol) = (kg/m^3)

**Comment by StefanPofahl** [comment]
Thanks for the fast response, I have corrected the error in the code snippet above.
Meanwhile, I figured out, how to retrieve the molar mass from the local component collection:
```
# And you can also load the JSON that teqp is loading for the pure fluids
pureJSON = teqp.collect_component_json(['Hydrogen'], teqp.get_datapath())[0]
molar_mass_ = pureJSON["TRANSPORT"]["viscosity"]["dilute"]["molar_mass"]
molar_mass_unit = pureJSON["TRANSPORT"]["viscosity"]["dilute"]["molar_mass_units"]
print("molar mass H2: ", molar_mass_, molar_mass_unit)
```

**Comment by ianhbell** [comment]
Right, but better would be to pull it from the pureJSON["EOS"][0]["molar_mass"] field which should always be present.

**Comment by StefanPofahl** [comment]
Syntax for Julia is:
```
molar_mass_H2 = teqp.collect_component_json(["Hydrogen"], string(teqp.get_datapath()))[1]["EOS"][1]["molar_mass"]
```
And what about `p` , where can I specify the pressure?

**Comment by ianhbell** [comment]
What do you mean, specify the pressure? teqp only supports T,D inputs because the T,p -> T,rho iterative calculation is more complicated than it appears.

**Comment by StefanPofahl** [comment]
Here an example under `CoolProp.jl` (Julia):
```
CoolProp.PropsSI("D", "T", temp_, "P", p_, "Hydrogen")
```
And for `Clapeyron.jl` (Julia):
```
Clapeyron.mass_density(eos_model_, p_, temp_)
```

**Comment by ianhbell** [comment]
Yes, this functionality is present in those libraries but not in teqp. In the simple case (pure fluids) it is relatively simple (I  was one of the primary developers of CoolProp), but in the general case it is not. So teqp makes you do that yourself. If you know an approximate density solution, it is just a Newton iteration.

**Comment by StefanPofahl** [comment]
Thanks for the support! :-)
Suggestion:
This could be a nice example for less experienced users of your package.

**Comment by ianhbell** [comment]
Good idea, please open a new issue with your recommendation and I'll think about it.
