### ISSUE TITLE
Add advanced cubic mixing rules

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/teqp#56]
See method from http://dx.doi.org/10.1016/j.fluid.2016.05.015, looks pretty easy to implement.

Not clear whether to build on existing cubic approach or whether to start fresh or build a very generalized approach with lots of variants and so on.

**Comment by longemen3000** [comment]
Jaulbert uses that mixing rule a lot:
 https://pubs.acs.org/doi/10.1021/acs.iecr.1c03003 (Wilson, van laar, UNIQUAC, NRTL) 
https://doi.org/10.1016/j.molliq.2023.122480 (GC-COSMOSAC)

**Comment by ianhbell** [comment]
@longemen3000 Is this model with advanced mixing rules and Wilson AC model implemented in Clapeyron.jl? I have some confusion and looking at Clapeyron.lj source would be helpful. I don't think it is implemented as best as I can tell.

**Comment by longemen3000** [comment]
It is implemented, in 0.5.3 (tcPR + mixing rule + residual Wilson), specifically, you can build that model with `tcPRW(args...)`
In theory, just Wilson suffices, (there is a specific `tcPRWilson` just with the parameters on the paper), but any Activity Model that defines `excess_g_res` could work too.
The mixing rule is implemented here: https://github.com/ClapeyronThermo/Clapeyron.jl/blob/master/src/models/cubic/mixing/gEr.jl

**Comment by ianhbell** [comment]
My question in particular is how one handles the molar volumes of the individual species since that is not documented in any of the papers as far as I can tell

**Comment by longemen3000** [comment]
![Screenshot_20230925-164146](https://github.com/usnistgov/teqp/assets/38795484/d5dd97e6-f090-41ae-8e54-c324654fc40d)
This?

**Comment by ianhbell** [comment]
Yes, but this is not what is implemented in Clapeyon, which uses a Rackett approach

**Comment by longemen3000** [comment]
we overload the function to specifically use the volumes provided by the EoS, here:
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/2de8ab7915dc63347dc547d5fa4c508e92968e6d/src/models/cubic/mixing/gEr.jl#L66-L70

**Comment by ianhbell** [comment]
In their paper they specifically use the covolume for v_i (minus the volume translation), so you might want to do the same
