### ISSUE TITLE
When mutant's basemodel falls out of scope, dangling references cause crashes

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/teqp#86]
I have no idea how to test that the base model is still alive. The destructor of the base model is called, but what is being pointed to is no longer a valid thing, so you can't call methods. This needs some thinking.

**Comment by ianhbell** [comment]
This is a tag of your problem @svenpohl1991

**Comment by ianhbell** [comment]
@svenpohl1991 can you remember how we got this to fail? I cannot reproduce the problem, and I wonder whether pybind11 has gotten smarter somehow about this. I looked into this: https://pybind11.readthedocs.io/en/latest/advanced/functions.html#call-policies but it seems perhaps like it is not needed?

**Comment by svenpohl1991** [comment]
The problem occurs when you create a basemodel in a class instance and build the mutant with this basemodel and do not store the base model in the class instance.

def some_class()
      base_model = make_model()
      self.mutant = build_multifluid_mutant(base_model)

c = some_class()

-> here the problem shows up
c.get_Ar00(100,100,np.array([1.0])

**Comment by ianhbell** [comment]
Can you make your example runnable and failing with most updated teqp?

**Comment by svenpohl1991** [comment]
Actually I cant reproduce the error with the most updated teqp version, so maybe the issue can be closed.

**Comment by ianhbell** [comment]
Yes, I couldn't reproduce either. I don't know why, because I didn't do anything smart on my side, even if there are tools available to make this less problematic. Let's close it for now, and if you can reproduce later, re-open.
