### ISSUE TITLE
adding composition derivatives of the reduced Helmholtz energy to tepq

### ISSUE THREAD

**Issue by fefiedler** [usnistgov/teqp#91]
I need derivatives of the following type, where $\mathbf{Z}$ is the composition vector and the indices $i,j,k$ correspond to the components in the mixture. $z$ is the derivative "depth".

$$\Lambda^r_{xyz_i} = (1/T)^x(\rho)^y\left(\frac{\partial^{x+y+z_i}(\alpha^r)}{\partial (1/T)^x\partial \rho^y \partial \mathbf{Z}_i^{z_i}   \}\right)$$

Here, a maximum $z_i$ of 2 is needed. Further mixed composition derivatives would be handy.

$$\Lambda^r_{xyz_i z_j } = (1/T)^x(\rho)^y\left(\frac{\partial^{x+y+z_i+z_j}(\alpha^r)}{\partial (1/T)^x\partial \rho^y \partial \mathbf{Z}_i^{z_i} \partial \mathbf{Z}_j^{z_j}  \}\right)$$

$$\Lambda^r_{xyz_i z_j z_k} = (1/T)^x(\rho)^y\left(\frac{\partial^{x+y+z_i+z_j+z_k}(\alpha^r)}{\partial (1/T)^x\partial \rho^y \partial \mathbf{Z}_i^{z_i} \partial \mathbf{Z}_j^{z_j} \partial \mathbf{Z}_k^{z_k}   \}\right)$$

Only cases are needed where at least two of $z_i, z_j, z_k = 1$.

**Comment by ianhbell** [comment]
Also need the same quantities with $\tau=T_{red}(x)/T$ and $\delta=\rho/\rho_{red}(x)$ as working variables; requires a slightly different approach
